package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
)

const (
	magic1st      = "LUKS\xba\xbe"
	magic2nd      = "SKUL\xba\xbe"
	magicLen      = 6
	uuidLen       = 40
	labelLen      = 48
	saltLen       = 64
	cSumAlgLen    = 32
	cSumLen       = 64
	uint16Len     = 2
	uint64Len     = 8
	binHeaderLen  = 512
	jsonOffset    = 4096
	minHeaderSize = 16384
	algoSHA256    = "sha256"
)

var possibleHeaderOffset = [9]uint64{16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304}
var luksVers = map[string]uint{magic1st: 1, magic2nd: 2}

type readHeaderError error

var (
	ErrUnsuppLUKS1 = readHeaderError(fmt.Errorf("LUKS1 is not supported"))
	ErrBinHeader   = readHeaderError(fmt.Errorf("Binary header not found"))
	ErrJSONHeader  = readHeaderError(fmt.Errorf("JSON header not found"))
	ErrInvalidCsum = readHeaderError(fmt.Errorf("Checksum is not valid"))
)

type LUKSBinaryHeader struct {
	Magic        [6]byte
	HeaderNumber uint
	Version      uint16

	// hdr size contains the size of the header with the JSON data area. The
	// offset and size of the secondary header must match this size. It is a
	// prevention to rewrite of a header with a different JSON area size
	HdrSize uint64

	// seqid is a counter (sequential number) that is always increased when a
	// new update of the header is written. The header with a higher seqid is
	// more recent and is used for recovery (if there are primary and secondary
	// headers with different seqid, the more recent one is automatically used)
	SeqId uint64

	// label is an optional label (similar to a filesystem label)
	Label        string
	CheckSumAlgo string

	// salt is generated by an RNG and is different for every header (it differs on
	// the primary and secondary header), even the backup header must contain
	// a different salt. The salt is not used after the binary header is read,
	// the main intention is to avoid deduplication of the header sector. The salt
	// must be regenerated on every header repair (but not on a regular update)
	Salt [64]byte

	// uuid is device UUID with the same format as in LUKS1
	UUID      string
	Subsystem [48]byte

	// hdr offset must match the physical header offset on the device (in bytes).
	// If it does not match, the header is misplaced and must not be used. It is a
	// prevention to partition resize or manipulation with the device start offset
	HdrOffset uint64

	// csum contains a checksum calculated with the csum alg algorithm. If the
	// checksum algorithm tag is shorter than the csum field length, the rest of
	// this field must be zeroed
	CheckSum [64]byte

	// Raw binary data
	Raw []byte
}

func (h LUKSBinaryHeader) String() string {
	// Get only not null bytes from the salt
	salt := h.Salt[:]
	for i, b := range h.Salt {
		if b == 0 {
			salt = h.Salt[:i]
			break
		}
	}
	// Convert salt to base64
	saltBase64 := base64.StdEncoding.EncodeToString(salt)

	checkSum := h.CheckSum[:]
	for i, b := range h.CheckSum {
		if b == 0 {
			checkSum = h.CheckSum[:i]
			break
		}
	}
	checkSumBase64 := base64.StdEncoding.EncodeToString(checkSum)

	return fmt.Sprintf("Binary Header:\n\tHeaderNumber: %d\n\tVersion: %d\n\tHdrSize: %d\n\tSeqId: %d\n\tLabel: %s\n\tCheckSumAlgo: %s\n\tSalt: %s\n\tUUID: %s\n\tSubsystem: %s\n\tHdrOffset: %d\n\tCheckSum: %s\n",
		h.HeaderNumber, h.Version, h.HdrSize, h.SeqId, h.Label, h.CheckSumAlgo, saltBase64, h.UUID, h.Subsystem, h.HdrOffset, checkSumBase64)
}

// ToRaw converts the binary header to raw binary data
func (h LUKSBinaryHeader) ToRaw() []byte {
	raw := make([]byte, binHeaderLen)

	copy(raw, h.Magic[:])                                 // Magick is the first 6 bytes
	binary.BigEndian.PutUint16(raw[6:8], h.Version)       // Version is 2 bytes
	binary.BigEndian.PutUint64(raw[8:16], h.HdrSize)      // HdrSize is 8 bytes
	binary.BigEndian.PutUint64(raw[16:24], h.SeqId)       // SeqId is 8 bytes
	copy(raw[24:72], []byte(h.Label))                     // Label is 48 bytes
	copy(raw[72:104], []byte(h.CheckSumAlgo))             // CheckSumAlgo is 32 bytes
	copy(raw[104:168], h.Salt[:])                         // Salt is 64 bytes
	copy(raw[168:208], []byte(h.UUID))                    // UUID is 40 bytes
	copy(raw[208:256], h.Subsystem[:])                    // Subsystem is 48 bytes
	binary.BigEndian.PutUint64(raw[256:264], h.HdrOffset) // HdrOffset is 8 bytes
	copy(raw[264:448], make([]byte, 184))                 // Zeroed 184 bytes
	copy(raw[448:binHeaderLen], h.CheckSum[:])            // CheckSum is 64 bytes

	return raw
}

type byteSlice []byte

func (b byteSlice) ToStr() string {
	res := make([]byte, 0, len(b))
	for _, v := range b {
		if v == 0 {
			break
		}
		res = append(res, v)
	}
	return string(res)
}

type LUKSJSONHeader struct {
	Config   ConfigS              `json:"config"`
	Digests  map[string]DigestsS  `json:"digests"`
	KeySlots map[string]KeySlotsS `json:"keyslots"`
	Segments map[string]SegmentsS `json:"segments"`
	Tokens   map[string]TokensS   `json:"tokens"`
	Raw      []byte               `json:"-"` // Raw JSON data
}

func (h LUKSJSONHeader) String() string {
	var digests string
	for k, v := range h.Digests {
		digests += fmt.Sprintf("\n\t\t\"%s\": %s,", k, v)
	}

	keySlots := ""
	for k, v := range h.KeySlots {
		keySlots += fmt.Sprintf("\n\t\t\"%s\": %s,", k, v)
	}

	segments := ""
	for k, v := range h.Segments {
		segments += fmt.Sprintf("\n\t\t\"%s\": %s,", k, v)
	}

	return fmt.Sprintf("JSON Header:\n\tConfig: %s\n\tDigests: %s\n\tKeySlots: %s\n\tSegments: %s\n\tTokens: %s\n",
		h.Config, digests, keySlots, segments, h.Tokens)
}

type ConfigS struct {
	JsonSize     string   `json:"json_size"`
	KeySlotsSize string   `json:"keyslots_size"`
	Flags        []string `json:"flags"`
}

func (c ConfigS) String() string {
	return fmt.Sprintf("{\n\t\tJsonSize: %s\n\t\tKeySlotsSize: %s\n\t\tFlags: %v\n\t}",
		c.JsonSize, c.KeySlotsSize, c.Flags)
}

type DigestsS struct {
	Type       string   `json:"type"`
	Keyslots   []string `json:"keyslots"`
	Segments   []string `json:"segments"`
	Hash       string   `json:"hash"`
	Iterations int      `json:"iterations"`
	Salt       string   `json:"salt"`
	Digest     string   `json:"digest"`
}

func (d DigestsS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeyslots: %v\n\t\t\tSegments: %v\n\t\t\tHash: %s\n\t\t\tIterations: %d\n\t\t\tSalt: %s\n\t\t\tDigest: %s\n\t\t}",
		d.Type, d.Keyslots, d.Segments, d.Hash, d.Iterations, d.Salt, d.Digest)
}

type KeySlotsS struct {
	Type    string `json:"type"`
	KeySize int    `json:"key_size"`
	// Af      struct {
	// 	Type    string `json:"type"`
	// 	Stripes int    `json:"stripes"`
	// 	Hash    string `json:"hash"`
	// } `json:"af"`
	Area struct {
		Type       string `json:"type"`
		Encryption string `json:"encryption"`
		KeySize    int    `json:"key_size"`
		Offset     string `json:"offset"`
		Size       string `json:"size"`
	} `json:"area"`
	Kdf struct {
		Type   string `json:"type"`
		Time   int    `json:"time"`
		Memory int    `json:"memory"`
		Cpus   int    `json:"cpus"`
		Salt   string `json:"salt"`
	} `json:"kdf"`
}

func (k KeySlotsS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeySize: %d\n\t\t\tArea: %+v\n\t\t\tKdf: %+v\n\t\t}",
		k.Type, k.KeySize, k.Area, k.Kdf)
}

type SegmentsS struct {
	Type       string `json:"type"`
	Offset     string `json:"offset"`
	IvTRweak   string `json:"iv_tweak"`
	Size       string `json:"size"`
	Encryption string `json:"encryption"`
	SectorSize int    `json:"sector_size"`
}

func (s SegmentsS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tOffset: %s\n\t\t\tIvTRweak: %s\n\t\t\tSize: %s\n\t\t\tEncryption: %s\n\t\t\tSectorSize: %d\n\t\t}",
		s.Type, s.Offset, s.IvTRweak, s.Size, s.Encryption, s.SectorSize)
}

type TokensS struct {
	Type           string   `json:"type"`
	KeySlots       []string `json:"keyslots"`
	KeyDescription string   `json:"key_description"`
}

func (t TokensS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeySlots: %v\n\t\t\tKeyDescription: %s\n\t\t}",
		t.Type, t.KeySlots, t.KeyDescription)
}

func main() {
	log.SetFlags(log.Lmsgprefix)
	// Get the cli attributes
	args := os.Args
	if len(args) < 2 {
		log.Fatalf("Usage: %s <file>\n", args[0])
	}

	file := NewFileReader(args[1])
	defer file.Close()

	binHeader1, jsonHeader1, err1 := readHeaders(file, 0)
	if !errors.Is(err1, ErrBinHeader) {
		log.Println("INFO: First LUKS binary header found")
		log.Println(binHeader1)
		if errors.Is(err1, ErrInvalidCsum) {
			log.Println("WARN: Checksum is not valid")
		} else {
			log.Println("INFO: Checksum is valid")
		}
	} else {
		log.Println("WARN: First binary header not found")
	}
	if !errors.Is(err1, ErrJSONHeader) {
		log.Println("INFO: First LUKS JSON header found")
		log.Println(jsonHeader1)
	} else {
		log.Println("WARN: First JSON header not found")
	}

	hdr1Sizes := make([]uint64, 0, len(possibleHeaderOffset))
	if binHeader1.Version == 2 && binHeader1.HdrSize > 0 {
		hdr1Sizes = append(hdr1Sizes, binHeader1.HdrSize)
	} else {
		hdr1Sizes = possibleHeaderOffset[:]
	}

	var binHeader2 LUKSBinaryHeader
	var jsonHeader2 LUKSJSONHeader
	var err2 error
	for _, hdrSize := range hdr1Sizes {
		binHeader2, jsonHeader2, err2 = readHeaders(file, int64(hdrSize))
		if !errors.Is(err2, ErrBinHeader) || !errors.Is(err2, ErrJSONHeader) {
			break
		}
	}
	if !errors.Is(err2, ErrBinHeader) {
		log.Println("INFO: Second LUKS binary header found")
		log.Println(binHeader2)
		if errors.Is(err2, ErrInvalidCsum) {
			log.Println("WARN: Checksum is not valid")
		} else {
			log.Println("INFO: Checksum is valid")
		}
	} else {
		log.Println("WARN: Second binary header not found")
	}
	if !errors.Is(err2, ErrJSONHeader) {
		log.Println("INFO: Second LUKS JSON header found")
		log.Println(jsonHeader2)
	} else {
		log.Println("WARN: Second JSON header not found")
	}

	if errors.Is(err1, ErrJSONHeader) && errors.Is(err2, ErrJSONHeader) {
		log.Fatalln("No JSON headers found. Header can't be restored")
	}

	// fmt.Printf("\nInput file name to save header: ")
	// var restoredHeaderFileName string
	// fmt.Scan(&restoredHeaderFileName)

	// if errors.Is(err1, ErrBinHeader) && errors.Is(err2, ErrBinHeader) {
	// 	// We need luks disk UUID
	// }
}

// func calculateChecksum(data []byte) []byte {
// }

func readHeaders(file *fileReader, headerOffset int64) (LUKSBinaryHeader, LUKSJSONHeader, error) {
	var resErr error

	// Read the binary header
	binHeader := binData2LUKSBinaryHeader(file.MustReadFrom(headerOffset, binHeaderLen))
	switch binHeader.Version {
	case 0:
		resErr = errors.Join(resErr, ErrBinHeader)
	case 1:
		resErr = errors.Join(resErr, ErrUnsuppLUKS1)
	}

	// Collect possible header sizes
	hdrSizes := make([]uint64, 0, len(possibleHeaderOffset))
	if binHeader.Version == 2 && binHeader.HdrSize > 0 {
		hdrSizes = append(hdrSizes, binHeader.HdrSize)
	} else {
		hdrSizes = possibleHeaderOffset[:]
	}

	// Read the JSON header
	var jsonHeader LUKSJSONHeader
	var err error
	for _, hdrSize := range hdrSizes {
		// fmt.Printf("Trying to read JSON header starting from %d with size %d\n", headerOffset+jsonOffset, hdrSize-jsonOffset)
		jsonHeader, err = readJSONHeader(file, headerOffset+jsonOffset, int64(hdrSize)-jsonOffset)
		if err == nil {
			break
		}
	}
	if err != nil {
		resErr = errors.Join(resErr, ErrJSONHeader)
	}

	if resErr == nil {
		if !isChecksumValid(binHeader, jsonHeader) {
			resErr = errors.Join(resErr, ErrInvalidCsum)
		}
	}

	return binHeader, jsonHeader, resErr
}

func isChecksumValid(binHeader LUKSBinaryHeader, jsonHeader LUKSJSONHeader) bool {
	expectedCheckSum := binHeader.CheckSum

	binHeader.CheckSum = [64]byte{} // Zero out the checksum
	var actualCheckSum [64]byte

	// Check sum algorithm
	if binHeader.CheckSumAlgo == algoSHA256 {
		binHeaderRaw := binHeader.ToRaw()
		binHeaderRaw = append(binHeaderRaw, make([]byte, jsonOffset-len(binHeaderRaw))...)
		jsonHeaderRaw := jsonHeader.Raw
		jsonHeaderRaw = append(jsonHeaderRaw, make([]byte, binHeader.HdrSize-uint64(len(jsonHeaderRaw)))...)
		fmt.Printf("Bin header len: %d\n", len(binHeaderRaw))
		fmt.Printf("JSON header len: %d\n", len(jsonHeaderRaw))
		checkSum := sha256.Sum256(append(binHeaderRaw, jsonHeaderRaw...))
		copy(actualCheckSum[:], checkSum[:])
	} else {
		fmt.Printf("Checksum algorithm '%s' is not supported\n", binHeader.CheckSumAlgo)
		fmt.Printf("Supported algorithms: '%s'\n", algoSHA256)
		fmt.Println([]byte(binHeader.CheckSumAlgo))
		fmt.Println([]byte(algoSHA256))
		return false
	}

	if !bytes.Equal(expectedCheckSum[:], actualCheckSum[:]) {
		fmt.Printf("Checksum is not valid\n")
		fmt.Printf("Expected: %v\n", expectedCheckSum)
		fmt.Printf("Actual: %v\n", actualCheckSum)
		return false
	}

	return true
}

func binData2LUKSBinaryHeader(raw []byte) LUKSBinaryHeader {
	headerRaw := InitLUKSHeaderRaw(raw)

	headerMagic := headerRaw.Read(magicLen)
	if string(headerMagic) != magic1st && string(headerMagic) != magic2nd {
		return LUKSBinaryHeader{}
	}

	res := LUKSBinaryHeader{
		Magic:        [6]byte(headerMagic),
		Version:      binary.BigEndian.Uint16(headerRaw.Read(uint16Len)),
		HdrSize:      binary.BigEndian.Uint64(headerRaw.Read(uint64Len)),
		SeqId:        binary.BigEndian.Uint64(headerRaw.Read(uint64Len)),
		Label:        headerRaw.Read(labelLen).ToStr(),
		CheckSumAlgo: headerRaw.Read(cSumAlgLen).ToStr(),
		Salt:         [64]byte(headerRaw.Read(saltLen)),
		UUID:         headerRaw.Read(uuidLen).ToStr(),
		Subsystem:    [48]byte(headerRaw.Read(labelLen)),
		HdrOffset:    binary.BigEndian.Uint64(headerRaw.Read(uint64Len)),
		CheckSum:     [64]byte(headerRaw.Skip(184).Read(cSumLen)),
		HeaderNumber: luksVers[string(headerMagic)],
		Raw:          raw,
	}

	tmpRaw := res.ToRaw()
	if !bytes.Equal(raw, tmpRaw) {
		fmt.Printf("Warning: Raw data does not match the original data\n")
		fmt.Printf("Original: %v\n", raw)
		fmt.Printf("Restored: %v\n", res.ToRaw())
	}

	return res
}

func readJSONHeader(file *fileReader, offset, hdrSize int64) (LUKSJSONHeader, error) {
	headerRaw := InitLUKSHeaderRaw(file.MustReadFrom(offset, hdrSize))

	rawJSONHeader := headerRaw.ReadUntilZeroChar()
	// rawJSONHeader := headerRaw.Read(int(hdrSize))

	res := LUKSJSONHeader{}
	if err := json.Unmarshal(rawJSONHeader, &res); err != nil {
		return LUKSJSONHeader{}, err
	}
	res.Raw = rawJSONHeader

	return res, nil
}

type LUKSRawHeader struct {
	Data []byte
	Pos  int
}

func InitLUKSHeaderRaw(data []byte) LUKSRawHeader {
	return LUKSRawHeader{
		Data: data,
		Pos:  0,
	}
}

func (h *LUKSRawHeader) Read(size int) byteSlice {
	// Check if the size is greater than the data length
	if h.Pos+size > len(h.Data) {
		fmt.Println("Error reading header: size is greater than the data length.")
		fmt.Printf("Current Pos: %d, Size: %d, Data length: %d\n", h.Pos, size, len(h.Data))
		return []byte{}
	}
	data := h.Data[h.Pos : h.Pos+size]
	h.Pos += size
	return data
}

func (h *LUKSRawHeader) ReadUntilZeroChar() []byte {
	// Find the position of the first zero character
	zeroPos := h.Pos
	for zeroPos < len(h.Data) {
		if h.Data[zeroPos] == 0 {
			break
		}
		zeroPos++
	}
	data := h.Data[h.Pos:zeroPos]
	h.Pos = zeroPos + 1
	return data
}

func (h *LUKSRawHeader) Skip(size int) *LUKSRawHeader {
	h.Pos += size
	return h
}

func (h *LUKSRawHeader) SkipUpTo(pos int) *LUKSRawHeader {
	h.Pos = pos
	return h
}

type fileReader struct {
	file *os.File
	pos  int64
}

func NewFileReader(fileName string) *fileReader {
	// Open the file in read mode
	file, err := os.Open(fileName)
	if err != nil {
		log.Fatal(err)
	}

	return &fileReader{
		file: file,
	}
}

func (f *fileReader) seek(offset int64) {
	var err error
	f.pos, err = f.file.Seek(offset, 0)
	if err != nil {
		log.Fatal(err)
	}
}

func (f *fileReader) read(size int64) []byte {
	// Read the data
	data := make([]byte, size)
	n, err := f.file.Read(data)
	if err != nil {
		log.Fatal(err)
	}

	// Check if the read data is the same as the requested size
	if int64(n) != size {
		log.Fatalf("Expected to read %d bytes, but read %d bytes", size, n)
	}

	f.pos += size

	return data
}

func (f *fileReader) MustReadFrom(from, size int64) []byte {
	// Seek to the start position
	f.seek(from)

	return f.read(size)
}

func (f *fileReader) MustRead(size int64) []byte {
	return f.read(size)
}

func (f *fileReader) Close() {
	f.file.Close()
}
