package main

import (
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"log"
	"os"
)

const (
	magic1st      = "LUKS\xba\xbe"
	magic2nd      = "SKUL\xba\xbe"
	magicLen      = 6
	uuidLen       = 40
	labelLen      = 48
	saltLen       = 64
	cSumAlgLen    = 32
	cSumLen       = 64
	uint16Len     = 2
	uint64Len     = 8
	binHeaderLen  = 512
	jsonOffset    = 4096
	minHeaderSize = 16384
)

var possibleSecondHeaderOffset = [9]int{16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304}

type LUKSBinaryHeader struct {
	Magic        [6]byte
	HeaderNumber uint
	Version      uint16

	// hdr size contains the size of the header with the JSON data area. The
	// offset and size of the secondary header must match this size. It is a
	// prevention to rewrite of a header with a different JSON area size
	HdrSize uint64

	// seqid is a counter (sequential number) that is always increased when a
	// new update of the header is written. The header with a higher seqid is
	// more recent and is used for recovery (if there are primary and secondary
	// headers with different seqid, the more recent one is automatically used)
	SeqId uint64

	// label is an optional label (similar to a filesystem label)
	Label        string
	CheckSumAlgo string

	// salt is generated by an RNG and is different for every header (it differs on
	// the primary and secondary header), even the backup header must contain
	// a different salt. The salt is not used after the binary header is read,
	// the main intention is to avoid deduplication of the header sector. The salt
	// must be regenerated on every header repair (but not on a regular update)
	Salt [64]byte

	// uuid is device UUID with the same format as in LUKS1
	UUID      string
	Subsystem [48]byte

	// hdr offset must match the physical header offset on the device (in bytes).
	// If it does not match, the header is misplaced and must not be used. It is a
	// prevention to partition resize or manipulation with the device start offset
	HdrOffset uint64

	// csum contains a checksum calculated with the csum alg algorithm. If the
	// checksum algorithm tag is shorter than the csum field length, the rest of
	// this field must be zeroed
	CheckSum [64]byte
}

func (h LUKSBinaryHeader) String() string {
	// Get only not null bytes from the salt
	salt := h.Salt[:]
	for i, b := range h.Salt {
		if b == 0 {
			salt = h.Salt[:i]
			break
		}
	}
	// Convert salt to base64
	saltBase64 := base64.StdEncoding.EncodeToString(salt)

	checkSum := h.CheckSum[:]
	for i, b := range h.CheckSum {
		if b == 0 {
			checkSum = h.CheckSum[:i]
			break
		}
	}
	checkSumBase64 := base64.StdEncoding.EncodeToString(checkSum)

	return fmt.Sprintf("Binary Header:\n\tHeaderNumber: %d\n\tVersion: %d\n\tHdrSize: %d\n\tSeqId: %d\n\tLabel: %s\n\tCheckSumAlgo: %s\n\tSalt: %s\n\tUUID: %s\n\tSubsystem: %s\n\tHdrOffset: %d\n\tCheckSum: %s\n",
		h.HeaderNumber, h.Version, h.HdrSize, h.SeqId, h.Label, h.CheckSumAlgo, saltBase64, h.UUID, h.Subsystem, h.HdrOffset, checkSumBase64)
}

type LUKSJSONHeader struct {
	Config   ConfigS              `json:"config"`
	Digests  map[string]DigestsS  `json:"digests"`
	KeySlots map[string]KeySlotsS `json:"keyslots"`
	Segments map[string]SegmentsS `json:"segments"`
	Tokens   map[string]TokensS   `json:"tokens"`
}

func (h LUKSJSONHeader) String() string {
	var digests string
	for k, v := range h.Digests {
		digests += fmt.Sprintf("\n\t\t\"%s\": %s,", k, v)
	}

	keySlots := ""
	for k, v := range h.KeySlots {
		keySlots += fmt.Sprintf("\n\t\t\"%s\": %s,", k, v)
	}

	segments := ""
	for k, v := range h.Segments {
		segments += fmt.Sprintf("\n\t\t\"%s\": %s,", k, v)
	}

	return fmt.Sprintf("JSON Header:\n\tConfig: %s\n\tDigests: %s\n\tKeySlots: %s\n\tSegments: %s\n\tTokens: %s\n",
		h.Config, digests, keySlots, segments, h.Tokens)
}

type ConfigS struct {
	JsonSize     string   `json:"json_size"`
	KeySlotsSize string   `json:"keyslots_size"`
	Flags        []string `json:"flags"`
}

func (c ConfigS) String() string {
	return fmt.Sprintf("{\n\t\tJsonSize: %s\n\t\tKeySlotsSize: %s\n\t\tFlags: %v\n\t}",
		c.JsonSize, c.KeySlotsSize, c.Flags)
}

type DigestsS struct {
	Type       string   `json:"type"`
	Keyslots   []string `json:"keyslots"`
	Segments   []string `json:"segments"`
	Hash       string   `json:"hash"`
	Iterations int      `json:"iterations"`
	Salt       string   `json:"salt"`
	Digest     string   `json:"digest"`
}

func (d DigestsS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeyslots: %v\n\t\t\tSegments: %v\n\t\t\tHash: %s\n\t\t\tIterations: %d\n\t\t\tSalt: %s\n\t\t\tDigest: %s\n\t\t}",
		d.Type, d.Keyslots, d.Segments, d.Hash, d.Iterations, d.Salt, d.Digest)
}

type KeySlotsS struct {
	Type    string `json:"type"`
	KeySize int    `json:"key_size"`
	// Af      struct {
	// 	Type    string `json:"type"`
	// 	Stripes int    `json:"stripes"`
	// 	Hash    string `json:"hash"`
	// } `json:"af"`
	Area struct {
		Type       string `json:"type"`
		Encryption string `json:"encryption"`
		KeySize    int    `json:"key_size"`
		Offset     string `json:"offset"`
		Size       string `json:"size"`
	} `json:"area"`
	Kdf struct {
		Type   string `json:"type"`
		Time   int    `json:"time"`
		Memory int    `json:"memory"`
		Cpus   int    `json:"cpus"`
		Salt   string `json:"salt"`
	} `json:"kdf"`
}

func (k KeySlotsS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeySize: %d\n\t\t\tArea: %+v\n\t\t\tKdf: %+v\n\t\t}",
		k.Type, k.KeySize, k.Area, k.Kdf)

	// return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeySize: %d\n\t\t\tAf: %+v\n\t\t\tArea: %+v\n\t\t\tKdf: %+v\n\t\t}",
	// 	k.Type, k.KeySize, k.Af, k.Area, k.Kdf)
}

type SegmentsS struct {
	Type       string `json:"type"`
	Offset     string `json:"offset"`
	IvTRweak   string `json:"iv_tweak"`
	Size       string `json:"size"`
	Encryption string `json:"encryption"`
	SectorSize int    `json:"sector_size"`
}

func (s SegmentsS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tOffset: %s\n\t\t\tIvTRweak: %s\n\t\t\tSize: %s\n\t\t\tEncryption: %s\n\t\t\tSectorSize: %d\n\t\t}",
		s.Type, s.Offset, s.IvTRweak, s.Size, s.Encryption, s.SectorSize)
}

type TokensS struct {
	Type           string   `json:"type"`
	KeySlots       []string `json:"keyslots"`
	KeyDescription string   `json:"key_description"`
}

func (t TokensS) String() string {
	return fmt.Sprintf("{\n\t\t\tType: %s\n\t\t\tKeySlots: %v\n\t\t\tKeyDescription: %s\n\t\t}",
		t.Type, t.KeySlots, t.KeyDescription)
}

func main() {
	// Get the cli attributes
	args := os.Args
	if len(args) < 2 {
		log.Fatal("No file name provided. Exiting.")
	}

	// Get the file name from the cli
	fileName := args[1]

	// Open the file in read mode
	file, err := os.Open(fileName)
	if err != nil {
		log.Fatal(err)
	}

	// Close the file after the function ends
	defer file.Close()

	var headerStartSeek int64 = 0

	log.Println("INFO: Reading first LUKS binary header")
	firstBinHeader := readBinaryHeader(file, headerStartSeek)
	switch firstBinHeader.Version {
	case 1:
		log.Fatalln("ERROR: LUKS1 is not supported")
	case 2:
		log.Println("INFO: Reading first LUKS2 JSON header")
	default:
		log.Println("WARN: First LUKS2 binary header not found")
		// FIXME: Try to find the second header
	}
	hdrSizes := make([]uint64, 0, len(possibleSecondHeaderOffset))
	if binHeader.HdrSize > 0 {
		hdrSizes = append(hdrSizes, binHeader.HdrSize)
	} else {
		hdrSizes = possibleSecondHeaderOffset
	}

	var firstJsonHeader LUKSJSONHeader
	for _, hdrSize := range hdrSizes {
		firstJsonHeader, err = readJSONHeader(file, headerStartSeek+jsonOffset, hdrSize)
		if err == nil {
			break
		}
	}

	log.Println("INFO: Reading second LUKS binary header")
		for _, offset := range possibleSecondHeaderOffset {
			binHeader = readBinaryHeader(file, int64(offset))
			if binHeader.HeaderNumber != 0 {
				headerStartSeek = int64(offset)
				break
			}
		}
	}
	// fmt.Println(binHeader)
}

func mustRead(file *os.File, length int) []byte {
	data := make([]byte, length)
	_, err := file.Read(data)
	if err != nil {
		log.Fatal(fmt.Printf("Error reading file: %v", err))
	}
	return data
}

func readBinaryHeader(file *os.File, offset int64) LUKSBinaryHeader {
	// Seek to the beginning of the file
	_, err := file.Seek(offset, 0)
	if err != nil {
		fmt.Printf("Error seeking file: %v\n", err)
	}

	// Read the first 6 binary bytes from the file
	headerMagic := mustRead(file, magicLen)
	if string(headerMagic) != magic1st && string(headerMagic) != magic2nd {
		log.Println("Not a LUKS header. Magic bytes mismatch. Binary header not found")
		return LUKSBinaryHeader{}
	}

	headerRaw := InitLUKSHeaderRaw(mustRead(file, binHeaderLen-magicLen))

	res := LUKSBinaryHeader{
		Magic:        [6]byte(headerMagic),
		Version:      binary.BigEndian.Uint16(headerRaw.Read(uint16Len)),
		HdrSize:      binary.BigEndian.Uint64(headerRaw.Read(uint64Len)),
		SeqId:        binary.BigEndian.Uint64(headerRaw.Read(uint64Len)),
		Label:        string(headerRaw.Read(labelLen)),
		CheckSumAlgo: string(headerRaw.Read(cSumAlgLen)),
		Salt:         [64]byte(headerRaw.Read(saltLen)),
		UUID:         string(headerRaw.Read(uuidLen)),
		Subsystem:    [48]byte(headerRaw.Read(labelLen)),
		HdrOffset:    binary.BigEndian.Uint64(headerRaw.Skip(184).Read(uint64Len)),
		CheckSum:     [64]byte(headerRaw.Read(cSumLen)),
		HeaderNumber: 1,
	}

	if string(headerMagic) == magic2nd {
		res.HeaderNumber = 2
	}

	return res
}

func readJSONHeader(file *os.File, offset int64, hdrSize uint64) LUKSJSONHeader {
	// Seek to the beginning of the file
	_, err := file.Seek(offset, 0)
	if err != nil {
		fmt.Printf("Error seeking file: %v\n", err)
	}

	readSize := hdrSize - jsonOffset
	headerRaw := InitLUKSHeaderRaw(mustRead(file, int(readSize)))

	res := LUKSJSONHeader{}
	if err := json.Unmarshal(headerRaw.ReadUntilZeroChar(), &res); err != nil {
		// fmt.Printf("Error unmarshalling JSON header: %v\n", err)
		return res, err
		// fmt.Println("Raw JSON: ", string(headerRaw.Data))
	}

	return res, nil
}

type LUKSRawHeader struct {
	Data []byte
	Pos  int
}

func InitLUKSHeaderRaw(data []byte) LUKSRawHeader {
	return LUKSRawHeader{
		Data: data,
		Pos:  0,
	}
}

func (h *LUKSRawHeader) Read(size int) []byte {
	// Check if the size is greater than the data length
	if h.Pos+size > len(h.Data) {
		fmt.Println("Error reading header: size is greater than the data length.")
		fmt.Printf("Current Pos: %d, Size: %d, Data length: %d\n", h.Pos, size, len(h.Data))
		return []byte{}
	}
	data := h.Data[h.Pos : h.Pos+size]
	h.Pos += size
	return data
}

func (h *LUKSRawHeader) ReadUntilZeroChar() []byte {
	// Find the position of the first zero character
	zeroPos := h.Pos
	for zeroPos < len(h.Data) {
		if h.Data[zeroPos] == 0 {
			break
		}
		zeroPos++
	}
	data := h.Data[h.Pos:zeroPos]
	h.Pos = zeroPos + 1
	return data
}

func (h *LUKSRawHeader) Skip(size int) *LUKSRawHeader {
	h.Pos += size
	return h
}

func (h *LUKSRawHeader) SkipUpTo(pos int) *LUKSRawHeader {
	h.Pos = pos
	return h
}
